### ISSUE TITLE
Failed To Download

### ISSUE THREAD

**Issue by Kalizo** [FireController1847/youtube-playlist-downloader#1] opened 2018-05-08 21:02 UTC
Hello to you !

Your project looks good but I meet a problem... For each videos of my playlist, it shows this error :

```
0 - ✗ Failed To Download "[FREE] Lil Uzi Vert Type Beat 2018 - "Promised" | Free Type Beat | Rap/Trap Instrumental 2018"
Error: ffmpeg exited with code 1: /Users/kalizo/Sites/youtube-playlist-downloader/src/audio/CashMoneyAp/[FREE] Lil Uzi Vert Type Beat 2018 - "Promised" | Free Type Beat | Rap/Trap Instrumental 2018.mp3: No such file or directory

    at ChildProcess.<anonymous> (/Users/kalizo/Sites/youtube-playlist-downloader/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```
I'm on MacOS with ffmpeg installed with Homebrew...

Thanks for your help !

**Comment by FireController1847** [comment] 2018-05-08 21:09
When typing `ffmpeg` in your terminal, does it work? This seems like it'd be an issue with it not being set to run on the command line

**Comment by FireController1847** [comment] 2018-05-08 21:09
Actually, now that I'm looking at it a second time,

**Comment by FireController1847** [comment] 2018-05-08 21:10
Actually, now that I'm looking at it a second time, this looks like an issue with your video title. I believe Mac OS doesn't allow pipes in their file names. Try using the main title remover to remove your pipes from the titles.

For reference, this is a pipe: `|`

**Comment by FireController1847** [comment] 2018-05-08 21:30
It could be another character. Basically, the issue is that FMMPEG cannot find the file that is supposed to be created to start the download. Usually, the file names are the same as the video title. Most of the time this happens when there are special characters in the title.

**Comment by Kalizo** [comment] 2018-05-08 21:38
Tested with titleRemoverMain to have just "Lil" for my final title file, it doesn't work. The problem come from elsewhere...

I will test another configuration of ffmpeg and i will post it here when i will find it ;) Thanks

**Comment by FireController1847** [comment] 2018-05-08 21:43
No problem! Sorry I wasn't able to directly find your issue

**Comment by FireController1847** [comment] 2018-05-13 22:48
I'm going to close this for now, and if the issue re-appears with v3.0.0 feel free to re-open it.

**Closed by FireController1847** 2018-05-13 22:48 UTC
